### DISCUSSION TITLE
I can't enable SSO with Gitlab and dex

### DISCUSSION THREAD

**Discussion by midestefanis** [argoproj-labs/argocd-autopilot#274] [Q&A]
Following the following documentation:

https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#dex
https://dexidp.io/docs/connectors/gitlab/

I'm trying to activate SSO with Gitlab but both the server and the dex always give me the following error:

time="2022-04-07T16:33:04Z" level=warning msg="invalid dex yaml config"

What I did was just edit the configmap 'argocd-cm'

```
data:
  url: https://****.com.ar/
  dex.config: |
    connectors:
      - type: gitlab
        id: gitlab
        name: GitLab
          baseURL: https://gitlab.com
          clientID: ****
          clientSecret: $argocd-secret-auth0:oidc.auth0.clientSecret
          redirectURI: https://****/dex/callback
          orgs:
          - name: ***
  repository.credentials: |
    - passwordSecret:
        key: git_token
        name: autopilot-secret
      url: https://gitlab.com/
      usernameSecret:
        key: git_username
        name: autopilot-secret
  timeout.reconciliation: 15s
```

Do I have to activate something else?
