### ISSUE TITLE
Support bootstrap with existing argocd installation

### ISSUE THREAD

**Issue by roi-codefresh** [argoproj-labs/argocd-autopilot#26]

**Comment by myspotontheweb** [comment]
This would be a DR scenario, restoring everything from scratch, for example:

```
minikube delete
minikbe create
argocd-autopilot repo bootstrap
```

Unfortunately this doesn't work. It seems autopilot assumes if must create the boostrap directory ;-( 

```
$ argocd-autopilot repo bootstrap --log-level debug
DEBU[2021-05-09T21:26:01+01:00] starting with options:                        kube-context=minikube namespace=argocd repo-url="https://github.com/myspotontheweb/argocd-demo1.git" revision=
DEBU[2021-05-09T21:26:01+01:00] detected namespace on kustomization, generating namespace.yaml file 
DEBU[2021-05-09T21:26:01+01:00] running bootstrap kustomization: apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  literals:
  - |
    repository.credentials=- passwordSecret:
        key: git_token
        name: autopilot-secret
      url: https://github.com/myspotontheweb/argocd-demo1.git
      usernameSecret:
        key: git_username
        name: autopilot-secret
  name: argocd-cm
kind: Kustomization
namespace: argocd
resources:
- github.com/argoproj-labs/argocd-autopilot/manifests?ref=v0.1.6
- namespace.yaml
  bootstrapKustPath=/tmp/auto-pilot786560654/kustomization.yaml resourcePath="github.com/argoproj-labs/argocd-autopilot/manifests?ref=v0.1.6"
INFO[2021-05-09T21:26:04+01:00] cloning repo: https://github.com/myspotontheweb/argocd-demo1.git 
DEBU[2021-05-09T21:26:04+01:00] cloning git repo                              rev= url="https://github.com/myspotontheweb/argocd-demo1.git"
Enumerating objects: 12, done.
Counting objects: 100% (12/12), done.
Compressing objects: 100% (9/9), done.
Total 12 (delta 1), reused 12 (delta 1), pack-reused 0
INFO[2021-05-09T21:26:04+01:00] using revision: "", installation path: ""    
FATA[2021-05-09T21:26:04+01:00] folder bootstrap already exist in: /bootstrap 
```

**Comment by omidb** [comment]
It will be extremely useful to have a command that does all of the above!

**Comment by StefanDanielSchwarz** [comment]
Thanks to the comments by @myspotontheweb and @noam-codefresh I've been able to re-bootstrap argocd-autopilot with these commands:

```
# Clone repo
git clone …

# Namespace: argocd
kubectl create namespace argocd

# Recreate the autopilot secret
kubectl -n argocd create secret generic autopilot-secret --from-literal git_username=username --from-literal git_token=…

# Bootstrap ArgoCD
kubectl apply -k argocd-autopilot_home-server/bootstrap/argo-cd

# Application: autopilot-bootstrap
cat <<EOF | kubectl apply -f -
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/managed-by: argocd-autopilot
    app.kubernetes.io/name: autopilot-bootstrap
  name: autopilot-bootstrap
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /status
    kind: Application
  project: default
  source:
    path: bootstrap
    repoURL: https://github.com/StefanDanielSchwarz/argocd-autopilot_home-server.git
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
EOF

# Get the admin password
kubectl get secret argocd-initial-admin-secret -n argocd -o go-template='{{printf "%s\n" (index (index . "data") "password" | base64decode)}}'
```

The autopilot-bootstrap application pulls in everything else from the online repo. You can check/watch with `kubectl get -n argocd applications,applicationsets` how all the other applications/applicationsets get restored.

Of course it would still be best if we could simply use `argocd-autopilot repo bootstrap` with an existing repo to re-boostrap. But until that's implemented, at least the above commands provide a complete workaround.
