### ISSUE TITLE
Infinite HTTPS redirect loop when installing on GKE

### ISSUE THREAD

**Issue by MarsOrBust24** [argoproj-labs/argocd-autopilot#297]
I followed the instructions on GKE AutoPilot through GCP Cloud Shell's IDE. Unfortunately at the very last step, the portforward, the exposed 80 port seems to just redirect to the snakeoil TLS port. CloudShell's secure reverse proxy only supports the HTTP protocol. Looking through the configs there seems to be no obvious way to disable the redirect. I know how to do it on the vanilla argocd-server yaml.

```
Environment: GKE Autopilot
K8s Version: 1.21
Host: GCP CloudShell 
Response code: 307
Location: https://8080-cs-646520168256-default.cs-us-west1-pits.cloudshell.dev/?authuser=0
```

## Update:

This can't possibly be correct, and yet this is the default config! I have never seen a server that can terminate TLS and HTTP running on the same port, 8080 in this case.
![Screenshot 2022-05-05 16 14 08](https://user-images.githubusercontent.com/876076/167026671-e8e22e1d-9b5f-4a5e-99c5-45ae6ccdefc0.png)

https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
```
# Deployment:
        ports:
        - containerPort: 8080
        - containerPort: 8083
# Service:
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
```

## Update 2

This is partially addressed in the argocd-server docs, but the docs don't apply to autopilots' structure. Half of that page is telling people to add --insecure, but the default config isn't secure either as the certificate is not trusted, and it makes securing it harder. https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#disable-internal-tls

## Update 3

I managed to stop the loop with the following config:

```
apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  name: argocd-cm
  literals:
  - |
    repository.credentials=- passwordSecret:
        key: git_token
        name: autopilot-secret
      url: https://gitlab.com/
      usernameSecret:
        key: git_username
        name: autopilot-secret
- behavior: merge
  name: argocd-cmd-params-cm
  literals:
  - 'server.insecure=true'
  - 'server.repo.server.strict.tls=false'
  - 'server.repo.server.plaintext=true'
kind: Kustomization
namespace: argocd
resources:
- github.com/argoproj-labs/argocd-autopilot/manifests/base?ref=v0.3.6
# patchesStrategicMerge:
# - argocd-server.yaml

```

However, the service is still exposing two ports, one of which is named https but is http.
