### ISSUE TITLE
Document kustomization procedure

### ISSUE THREAD

**Issue by FossPrime** [argoproj-labs/argocd-autopilot#298]
Related to #38

Currently installing in AutoPilot will default to around $97/m in ADDITIONAL resources, for a bare-bones install. In this case, specifying resource requests is not usually optional. Yet, there is zero documentation on how to fix chart issues.

## Attempt 1
Here's what I got so far for a patchStrategicMerge:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  template:
    spec:
      containers:
      - args:
        - server
        - --namespaced
        - --auth-mode
        - server
        - --auth-mode
        - client
        - --secure=false
        env: []
        name: argo-server
        readinessProbe:
          httpGet:
            scheme: HTTP
```

and here's the error I get with that:
```
$ kustomize build argo-cd
Error: no matches for Id Deployment.v1.apps/argocd-server.argocd; failed to find unique target for patch Deployment.v1.apps/argocd-server.argocd
```

## Attempt 2
Having discovered that the deployment is preconfigured to load the argocd-cm ConfigMap, I attempted to patch it... but you're using some black-magic literal operators that I can't find any docs in. It's not yaml, json, or anything I've ever seen... You're mixing merge with `=- ` and a pseudo-yaml syntax.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  literals:
  - |
    server.repo.server.strict.tls: false
    repository.credentials=- passwordSecret:
        key: git_token
        name: autopilot-secret
      url: https://gitlab.com/
      usernameSecret:
        key: git_username
        name: autopilot-secret
  name: argocd-cm
kind: Kustomization
namespace: argocd
resources:
- github.com/argoproj-labs/argocd-autopilot/manifests/base?ref=v0.3.6
```

- I found some incomplete but semi-useful documentation from [this chinese website](https://www.bookstack.cn/read/kubernetes-kubectl-en/5e934a1e61ace3fb.md) 

## Partial Success

```
apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  name: argocd-cm
  literals:
  - |
    repository.credentials=- passwordSecret:
        key: git_token
        name: autopilot-secret
      url: https://gitlab.com/
      usernameSecret:
        key: git_username
        name: autopilot-secret
- behavior: merge
  name: argocd-cmd-params-cm
  literals:
  - 'server.insecure=true'
  - 'server.repo.server.strict.tls=false'
  - 'server.repo.server.plaintext=true'
kind: Kustomization
namespace: argocd
resources:
- github.com/argoproj-labs/argocd-autopilot/manifests/base?ref=v0.3.6
patchesStrategicMerge:
- set-argocd-resources.yaml
```

set-argocd-resources.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  template:
    spec:
      containers:
      - name: argocd-server
        resources:
          limits:
            cpu: 200m
            ephemeral-storage: 1Gi
            memory: 512Mi
          requests:
            cpu: 200m
            ephemeral-storage: 1Gi
            memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-server
        resources:
          limits:
            cpu: 200m
            ephemeral-storage: 1Gi
            memory: 512Mi
          requests:
            cpu: 100m
            ephemeral-storage: 1Gi
            memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
        - name: argocd-repo-server
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 1Gi
              memory: 512Mi
            requests:
              cpu: 100m
              ephemeral-storage: 1Gi
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis
spec:
  template:
    spec:
      containers:
      - name: redis
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 1Gi
            memory: 512Mi
          requests:
            cpu: 100m
            ephemeral-storage: 1Gi
            memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-notifications-controller
spec:
  template:
    spec:
      containers:
      - name: argocd-notifications-controller
        resources:
          limits:
            cpu: 200m
            ephemeral-storage: 1Gi
            memory: 512Mi
          requests:
            cpu: 100m
            ephemeral-storage: 1Gi
            memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
spec:
  template:
    spec:
      containers:
      - name: dex
        resources:
          limits:
            cpu: 200m
            ephemeral-storage: 1Gi
            memory: 512Mi
          requests:
            cpu: 100m
            ephemeral-storage: 1Gi
            memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-applicationset-controller
spec:
  template:
    spec:
      containers:
      - name: argocd-applicationset-controller
        resources:
          limits:
            cpu: 200m
            ephemeral-storage: 1Gi
            memory: 512Mi
          requests:
            cpu: 100m
            ephemeral-storage: 1Gi
            memory: 128Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
spec:
  template:
    spec:
      containers:
      - name: argocd-application-controller
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 1024Mi
          requests:
            cpu: 200m
            ephemeral-storage: 1Gi
            memory: 512Mi
```
