### ISSUE TITLE
Not able to apply annotations in particular application

### ISSUE THREAD

**Issue by NitishGupta9282** [argoproj-labs/argocd-autopilot#383]
Hi,

     I want to apply annotations on application level rather than project level. So i am trying to apply annotations in config.json file of my app, But annotations are not reflecting in UI, Its working fine when i applied annotations on project level. Code is attached below.
     
    `{
  "appName": "sample",
  "userGivenName": "sample",
  "destNamespace": "default",
  "destServer": "https://kubernetes.default.svc",
  "srcPath": "apps/sample/overlays/lab",
  "srcRepoURL": "https://github.com/NitishGupta9282/autop.git",
  "srcTargetRevision": "",
  "labels": null,
  "annotations":
        { 
         "op": "add",
          "test": "sample"
   }
}`

**Comment by philipsens** [comment]
I also wonder how this is supposed to work.

**Comment by philipsens** [comment]
Add `goTemplate: true` and add a `templatePatch` like this:
```yaml
templatePatch: |
  metadata:
    annotations:
      {{- range $key, $value := .annotations }}
      {{ $key }}: {{ $value }}
      {{- end }}
```
