### ISSUE TITLE
Introduce `reop upgrade` command

### ISSUE THREAD

**Issue by oren-codefresh** [argoproj-labs/argocd-autopilot#45]
argocd-autopilot will check whether a new version of argo-cd (and applicationset) is available (e.g. new tag is available) and will create a pull request to be applied on a giit (can also be automatic)

**Comment by todaywasawesome** [comment]
Yes please.

While waiting for this feature I just edited the kustomization in `bootstrap/argo-cd` to specify the Argo CD release I'm looking for.

**Comment by NiniiGit** [comment]
Having this feature would be of great help. In the meantime, I believe another approach to handle these upgrades would be,   to update the value of `ref=v0.3.5` from the `resources` section in below config file that get generated after bootstrapping ArgoCD, (which would be present in (your-gitrepo)**/bootstrap/argo-cd/kustomization.yaml** path) 

```
apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  literals:
  - |
    repository.credentials=- passwordSecret:
        key: git_token
        name: autopilot-secret
      url: https://github.com/
      usernameSecret:
        key: git_username
        name: autopilot-secret
  name: argocd-cm
kind: Kustomization
namespace: argocd
resources:
- github.com/argoproj-labs/argocd-autopilot/manifests/base?ref=v0.3.5
```
