### ISSUE TITLE
HelmChartInflationGenerator is detecting wrong kube cluster version

### ISSUE THREAD

**Issue by ThorstenKunz** [argoproj-labs/argocd-autopilot#507]
I am trying to deploy the following helm chart via kustomize:

```
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: rancher-server
name: rancher
repo: https://releases.rancher.com/server-charts/stable
version: 2.7.6
releaseName: rancher-server
namespace: cattle-system
valuesInline:
  replicas: 3
  hostname: rancher.xxxxxxxxxxx
  ingress:
    ingressClassName: nginx
    tls:
      source: secret
  certmanager:
    version: "1.13.0"
```

The chart has a `kubeVersion: < 1.27.0-0` requirement set. However the cluster is currently running version 1.26.6 so everything should be ok. But I am getting the following sync error in the ArgoCD UI:

```
[...] Error: chart requires kubeVersion: < 1.27.0-0 which is incompatible with Kubernetes v1.27.0 Use --debug flag to render out invalid YAML : unable to run: 'helm template rancher-server <path to cached source>/apps/rancher/base/charts/rancher --namespace cattle-system -f /tmp/kustomize-helm-200908178/rancher-kustomize-values.yaml' with env=[HELM_CONFIG_HOME=/tmp/kustomize-helm-200908178/helm HELM_CACHE_HOME=/tmp/kustomize-helm-200908178/helm/.cache HELM_DATA_HOME=/tmp/kustomize-helm-200908178/helm/.data] (is 'helm' installed?): exit status 1
```

ArgoCD version 2.8.4
