### ISSUE TITLE
argocd-autopilot deploy app nginx-ingress wrong name EndpointSlice stay in progress

### ISSUE THREAD

**Issue by rchekhina** [argoproj-labs/argocd-autopilot#548]
HI,

I have a strange behavior when I try to deploy ingress-nginx from autopilot with the following kustomization.yaml:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: ingress-nginx
  version: 4.9.0
  repo: https://kubernetes.github.io/ingress-nginx
  valuesFile: values.yaml
  namespace: ingress-nginx
  releaseName: ingress-nginx
resources:
  - ingress-nginx-ns.yaml
```
 
or with :

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.9.5/deploy/static/provider/cloud/deploy.yaml
```
when autopilot deploy the ingress-nginx it stay in progress because of the ingress-nginx-controller and if I look directly on kubernetes I can see that the EndpointSlice created as a different name. On argocd the name is ingress-nginx-controller-ztwxr and on kubernetes the name is ingress-nginx-controller-gcvmv:

![image](https://github.com/argoproj-labs/argocd-autopilot/assets/78473404/5bf7afc7-3691-4e41-8a99-d406cd34778d)

![image](https://github.com/argoproj-labs/argocd-autopilot/assets/78473404/f858a841-c8fb-4b09-898e-59dfb6d5fc6a)

if I delete the EndpointSlice from argocd a new name appear on argocd but nothing new on kubernetes.

I dont understand with the name is different between argocd and kubernetes. Can you help me please ?

Best regards.
