### ISSUE TITLE
How to specify ArgoCD version to use?

### ISSUE THREAD

**Issue by AlexEndris** [argoproj-labs/argocd-autopilot#557]
Hi,
currently, the version 0.4.17 of argocd-autopilot links to the install script in the master branch of the argocd repository. How can I specify which version of argocd (not autopilot) to use?

It would be very helpful if we could control updates and upgrades of argocd this way, instead of always linking to the master branch.

Maybe it's already possible, and I'm just missing something, but if not, that would be truly handy!

Thanks!

**Comment by diogosilva30** [comment]
I have the same question 🤔

**Comment by AlexEndris** [comment]
@noam-codefresh 
Is this also how you'd upgrade form a specific version to another one? If so, then this is what I've asked for.

**Comment by noam-codefresh** [comment]
after bootstrapping a new repository (with the default settings), the `bootstrap/argo-cd/kustomization.yaml` file will have a resource reference to `github.com/argoproj-labs/argocd-autopilot/manifests/base?ref=v0.4.17` (right now, when the autopilot stable version is `v0.4.17`)
that references [this](https://github.com/argoproj-labs/argocd-autopilot/blob/v0.4.17/manifests/base/kustomization.yaml) file.

if you replace this resource reference with `https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.6/manifests/install.yaml` (for example), it will replace your argo-cd installation to `v2.9.6`.

you will need to copy over the following patches into your repo's kustomzation file:
```yaml
configMapGenerator:
  - name: argocd-cm
    behavior: merge
    literals:
      - "timeout.reconciliation=15s"

patches:
  # reset the crbs to `subject.namespace: default`, so that argo-cd will later change them to the actual ns
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: default
```
the first patch will change the default reconciliation timeout to 15s. the second patch is important if you install to a non-default (`argocd`) namespace. if you do not have this patch, the clusterRoles will not give the permissions to the right serviceAccount.
