### ISSUE TITLE
Question about default timeout.reconciliation=15s

### ISSUE THREAD

**Issue by murand78** [argoproj-labs/argocd-autopilot#593]
Hi, when installing argcd with autopilot, looking at https://github.com/argoproj-labs/argocd-autopilot/blob/main/manifests/base/kustomization.yaml  apps are refreshed every 15s.

```
configMapGenerator:
  - name: argocd-cm
    behavior: merge
    literals:
      - "timeout.reconciliation=15s"
```

Reading https://argo-cd.readthedocs.io/en/stable/faq/#how-often-does-argo-cd-check-for-changes-to-my-git-or-helm-repository the argocd default is 180s.

Is there any reason why in argocd with autopilot installation this is set to default 12 time more quicker?
In my case I have 150 Applications generated with 20 ApplicationSet on a cluster with 4CPU/16GB Ram nodes, and compute resources were exhausted on the node used by the argocd-application-controller.
Reverting the default value to 180s significantly reduced the cpu consumption (the graph below after 11.00) .

<img width="1205" alt="Screenshot 2024-08-28 at 14 28 28" src="https://github.com/user-attachments/assets/8caa504b-b030-426c-8571-2bb5d84c4d27">
