### ISSUE TITLE
Using ignoreDifferences

### ISSUE THREAD

**Issue by dezren39** [argoproj-labs/argocd-autopilot#631]
How would I use ignoreDifferences for an app deployed from this tool? Since I've been using the json file I don't actually have an argo app where i can put these things right? Kustomize doesn't seem to have an alternate way for me to do it.

**Comment by dezren39** [comment]
i guess it would have to be a config.json value that mimics the equivalent yaml?

```
  "ignoreDifferences": [
    {
      "group": "apiextensions.k8s.io",
      "kind": "CustomResourceDefinition",
      "jqPathExpressions": [
        ".spec.versions[].additionalPrinterColumns[]"
      ]
    }
  ]
```
unfortunately patchops don't really seem to work well because my kustomize is to a helmChart. also sometimes you need to change things dynamically and being able to ignore them would really be nice.

**Comment by cnu80** [comment]
hi, I tried it with a "patch" for metallb deployments. But it doesn't work.
```

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: infra-metallb # Make sure this matches your Application name
      namespace: argocd
    patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: infra-metallb # Ensure this matches your Application name
        namespace: argocd
      spec:
        ignoreDifferences:
          - group: "apiextensions.k8s.io"
            kind: CustomResourceDefinition
            name: bgppeers.metallb.io
            jsonPointers:
              - /spec/conversion/webhook/clientConfig/caBundle
          - group: "apiextensions.k8s.io"
            kind: CustomResourceDefinition
            name: addresspools.metallb.io
            jsonPointers:
              - /spec/conversion/webhook/clientConfig/caBundle
        syncPolicy:
          automated:
            selfHeal: true
          syncOptions:
            - ServerSideApply=true
            - CreateNamespace=true
            - RespectIgnoreDifferences=true
```
