### ISSUE TITLE
Change `repository.credentials` in argocd-cm to declerative repositories for ArgoCD 3.0.0

### ISSUE THREAD

**Issue by philipsens** [argoproj-labs/argocd-autopilot#672]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd-autopilot version`.

**Describe the bug**

Since ArgoCD version 3.0.0 is it not possible to use the [legacy repo config](https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.14-3.0/#removed-support-for-legacy-repo-config-in-argocd-cm).

This results in the applications not being able to be synced, because the repository is unknown.

**To Reproduce**

Use the current version of ArgoCD Autopilot and use it to bootstrap the (stable) 3.0.0 version of ArgoCD.

**Expected behavior**

The new [declarative setup for repositories](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#repositories) should be used.

**Screenshots**

**Version**

```shell
❯ argocd-autopilot version
v0.4.19
```

**Logs**

```
ComparisonError
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = failed to list refs: authentication required: Repository not found.
```

**Comment by orange723** [comment]
same issues

**Comment by orange723** [comment]
I crate secret

example
```
apiVersion: v1
kind: Secret
metadata:
  name: github-https-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  password: "MyPAT"
  type: git
  url: https://github.com/owner/repo
  username: username
type: Opaque
```

and argocd is sync

thanks
